## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('q-smart-hybrid-example',
                                  ['q-smart-hybrid', 'internet', 'wifi', 'applications', 'stats', 'flow-monitor', 'config-store'])
    obj.source = 'q-smart-hybrid-example.cc'

    obj = bld.create_ns3_program('q-smart-hybrid-compare',
                                  ['q-smart-hybrid', 'internet', 'wifi', 'applications', 'flow-monitor', 'olsr'])
    obj.source = 'q-smart-hybrid-compare.cc'
