## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('smart-aodv-qlearning', ['internet', 'wifi'])
    module.includes = '.'
    module.source = [
        'model/smart-aodv-qlearning-id-cache.cc',
        'model/smart-aodv-qlearning-dpd.cc',
        'model/smart-aodv-qlearning-rtable.cc',
        'model/smart-aodv-qlearning-rqueue.cc',
        'model/smart-aodv-qlearning-packet.cc',
        'model/smart-aodv-qlearning-neighbor.cc',
        'model/smart-aodv-qlearning-qlearning.cc',
        'model/smart-aodv-qlearning-routing-protocol.cc',
        'helper/smart-aodv-qlearning-helper.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'smart-aodv-qlearning'
    headers.source = [
        'model/smart-aodv-qlearning-id-cache.h',
        'model/smart-aodv-qlearning-dpd.h',
        'model/smart-aodv-qlearning-rtable.h',
        'model/smart-aodv-qlearning-rqueue.h',
        'model/smart-aodv-qlearning-packet.h',
        'model/smart-aodv-qlearning-neighbor.h',
        'model/smart-aodv-qlearning-qlearning.h',
        'model/smart-aodv-qlearning-routing-protocol.h',
        'helper/smart-aodv-qlearning-helper.h',
        ]

    # Temporarily disable Python bindings
    # bld.ns3_python_bindings()
