## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('smart-aodv', ['internet', 'wifi'])
    module.includes = '.'
    module.source = [
        'model/smart-aodv-id-cache.cc',
        'model/smart-aodv-dpd.cc',
        'model/smart-aodv-rtable.cc',
        'model/smart-aodv-rqueue.cc',
        'model/smart-aodv-packet.cc',
        'model/smart-aodv-neighbor.cc',
        'model/smart-aodv-routing-protocol.cc',
        'helper/smart-aodv-helper.cc',
        ]

    # Temporarily disable tests to focus on core module
    # smart_aodv_test = bld.create_ns3_module_test_library('smart-aodv')
    # smart_aodv_test.source = [
    #     'test/aodv-id-cache-test-suite.cc',
    #     'test/aodv-test-suite.cc',
    #     'test/aodv-regression.cc',
    #     'test/bug-772.cc',
    #     'test/loopback.cc',
    #     ]

    # # Tests encapsulating example programs should be listed here
    # if (bld.env['ENABLE_EXAMPLES']):
    #     smart_aodv_test.source.extend([
    #         #   'test/aodv-examples-test-suite.cc',
    #             ])

    headers = bld(features='ns3header')
    headers.module = 'smart-aodv'
    headers.source = [
        'model/smart-aodv-id-cache.h',
        'model/smart-aodv-dpd.h',
        'model/smart-aodv-rtable.h',
        'model/smart-aodv-rqueue.h',
        'model/smart-aodv-packet.h',
        'model/smart-aodv-neighbor.h',
        'model/smart-aodv-routing-protocol.h',
        'helper/smart-aodv-helper.h',
        ]

    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

    # Temporarily disable Python bindings
    # bld.ns3_python_bindings()
